api_platform:
    title: 'Budget Tracker'
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    swagger:
        api_keys:
            bearer:
                name: Authorization
                type: header
